# Generated by Django 4.0.4 on 2022-05-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFullTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=200)),
                ('hours', models.IntegerField()),
                ('type', models.CharField(choices=[('Course', 'Course'), ('TA', 'TA'), ('Checker', 'Checker'), ('Support', 'Support')], max_length=200)),
                ('day', models.CharField(choices=[('Day1', 'Day1'), ('Day2', 'Day2'), ('Day3', 'Day3'), ('Day4', 'Day4'), ('Day5', 'Day5')], max_length=200)),
                ('moment', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=200)),
                ('week', models.CharField(choices=[('Week1', 'Week1'), ('Week2', 'Week2'), ('Week3', 'Week3'), ('Week4', 'Week4'), ('Week5', 'Week5'), ('Week6', 'Week6'), ('Week7', 'Week7'), ('Week8', 'Week8'), ('Week9', 'Week9'), ('Week10', 'Week10'), ('Week11', 'Week11'), ('Week12', 'Week12')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=200)),
                ('hours', models.IntegerField()),
                ('type', models.CharField(choices=[('Course', 'Course'), ('TA', 'TA'), ('Checker', 'Checker'), ('Support', 'Support')], max_length=200)),
                ('week', models.CharField(choices=[('Week1', 'Week1'), ('Week2', 'Week2'), ('Week3', 'Week3'), ('Week4', 'Week4'), ('Week5', 'Week5'), ('Week6', 'Week6'), ('Week7', 'Week7'), ('Week8', 'Week8'), ('Week9', 'Week9'), ('Week10', 'Week10'), ('Week11', 'Week11'), ('Week12', 'Week12'), ('Week13', 'Week13'), ('Week14', 'Week14'), ('Week15', 'Week15'), ('Week16', 'Week16'), ('Week17', 'Week17'), ('Week18', 'Week18'), ('Week19', 'Week19'), ('Week20', 'Week20'), ('Week21', 'Week21'), ('Week22', 'Week22'), ('Week23', 'Week23'), ('Week24', 'Week24')], max_length=200)),
                ('day', models.CharField(choices=[('Day1', 'Day1'), ('Day2', 'Day2'), ('Day3', 'Day3'), ('Day4', 'Day4'), ('Day5', 'Day5')], max_length=200)),
                ('moment', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField()),
                ('ta', models.IntegerField()),
                ('checker', models.IntegerField()),
                ('support', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StructurePartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_structure', models.CharField(max_length=200)),
                ('instructors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.courseparttime')),
            ],
        ),
        migrations.CreateModel(
            name='StructureFullTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_structure', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.coursefulltime')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramListPartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.structureparttime')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramListFullTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.structurefulltime')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('contract', models.CharField(choices=[('Employee', 'Employee'), ('Freelancer', 'Freelancer')], max_length=200)),
                ('devise', models.CharField(choices=[('ILS', 'ILS'), ('EUR', 'EUR'), ('MUR', 'MUR'), ('CFA', 'CFA'), ('USD', 'USD')], max_length=200)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.rate')),
            ],
        ),
    ]
