# Generated by Django 4.0.4 on 2022-06-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tali', '0003_courseparttime_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorFullTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_hour', models.IntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='programlistfulltime',
            name='instructors',
            field=models.ManyToManyField(through='tali.InstructorFullTime', to='tali.instructor'),
        ),
        migrations.AddField(
            model_name='instructorfulltime',
            name='programfulltime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.programlistfulltime'),
        ),
    ]
