# Generated by Django 4.0.4 on 2022-06-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tali', '0006_remove_programlistfulltime_instructors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorFullTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_hour', models.IntegerField(blank=True, default=0, null=True)),
                ('coursefulltime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.coursefulltime')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.instructor')),
            ],
        ),
    ]
