# Generated by Django 4.0.4 on 2022-06-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tali', '0007_instructorfulltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorfulltime',
            name='number_hour',
            field=models.IntegerField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tali.coursefulltime'), null=True),
        ),
    ]
